### ISSUE TITLE
psychmeta and R 4.0 on macOS: library(psychmeta) broken

### ISSUE THREAD

**Issue by dstanley4** [psychmeta/psychmeta#84]
Just a heads up that psychmeta doesn't seem to work on macOS after I upgraded to R 4.0.
I'm running the latest versions of R, RStudio, and macOS. I haven't encountered this problem with any other packages. I've deleted both R and R.frameworks directories - and then reinstalled R and RStudio. No luck. Perhaps the problem is related to your code checking to see if you are running the latest version of psychmeta that executes when you type the library command? See library command error in attached screenshot. I suspect it's not a problem specific to my system - though that is of course possible. I also installed the gmm packages after this failure - psychmeta still won't activate via library.

<img width="1009" alt="Screen Shot 2020-05-02 at 7 49 04 AM" src="https://user-images.githubusercontent.com/418534/80863330-7fa14c80-8c49-11ea-9f42-668a993db229.png">

**Comment by bwiernik** [comment]
Yes, there are some issues related to R 4.0 that we are currently working on. Thanks for the heads up.

**Comment by bwiernik** [comment]
Hi @dstanley4, I am not able to reproduce this problem. Can you please share output of `sessionInfo()` and also confirm that you have the issue with a fresh install of R? That error looks like a general R installation problem rather than something specific to psychmeta.

**Comment by bwiernik** [comment]
Also, @dstanley4 can you install xcode on your system from the Mac App Store (if you don't already have it) and try again?

**Comment by dstanley4** [comment]
Removed R as per sudo command at:
https://cran.r-project.org/doc/manuals/r-release/R-admin.html#Uninstalling-under-macOS

Restarted Mac. 
Using: 10.15.4 (19E287)
Using RStudio: Version 1.2.5042

installed R again.
Installed tidyverse.  (since that's a given)
Installed psychmeta 
library problem for psychmeta occurred again. See below. Includes Session info.

Attempted Xode thing:
Installed Xcode. Did first run to set it up.
Reinstalled psychmeta in R. 
Same problem.

A somewhat similar bug:
Reading this somewhat similar problem, I wonder is there related to path assumptions on the users machine that do not generalize:
https://github.com/rstudio/rstudio/issues/5238


> install.packages("psychmeta", dep = TRUE)
also installing the dependencies ‘zoo’, ‘sandwich’, ‘mvtnorm’, ‘gmm’, ‘humaniformat’, ‘tmvtnorm’, ‘metafor’, ‘nor1mix’, ‘data.table’, ‘bib2df’

trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/zoo_1.8-8.tgz'
Content type 'application/x-gzip' length 1079492 bytes (1.0 MB)
==================================================
downloaded 1.0 MB

trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/sandwich_2.5-1.tgz'
Content type 'application/x-gzip' length 1384011 bytes (1.3 MB)
==================================================
downloaded 1.3 MB

trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/mvtnorm_1.1-0.tgz'
Content type 'application/x-gzip' length 257711 bytes (251 KB)
==================================================
downloaded 251 KB

trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/gmm_1.6-4.tgz'
Content type 'application/x-gzip' length 1386205 bytes (1.3 MB)
==================================================
downloaded 1.3 MB

trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/humaniformat_0.6.0.tgz'
Content type 'application/x-gzip' length 531651 bytes (519 KB)
==================================================
downloaded 519 KB

trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/tmvtnorm_1.4-10.tgz'
Content type 'application/x-gzip' length 631996 bytes (617 KB)
==================================================
downloaded 617 KB

trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/metafor_2.4-0.tgz'
Content type 'application/x-gzip' length 2985832 bytes (2.8 MB)
==================================================
downloaded 2.8 MB

trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/nor1mix_1.3-0.tgz'
Content type 'application/x-gzip' length 127102 bytes (124 KB)
==================================================
downloaded 124 KB

trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/data.table_1.12.8.tgz'
Content type 'application/x-gzip' length 2070859 bytes (2.0 MB)
==================================================
downloaded 2.0 MB

trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/bib2df_1.1.1.tgz'
Content type 'application/x-gzip' length 62663 bytes (61 KB)
==================================================
downloaded 61 KB

trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/psychmeta_2.3.8.tgz'
Content type 'application/x-gzip' length 3008700 bytes (2.9 MB)
==================================================
downloaded 2.9 MB


The downloaded binary packages are in
	/var/folders/0q/428bg5mn6mv_g80qtjhn5jgm0000gn/T//RtmpHQAUH3/downloaded_packages
> library(psychmeta)
Error: package or namespace load failed for ‘psychmeta’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/gmm/libs/gmm.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/gmm/libs/gmm.so, 6): Library not loaded: /usr/local/gfortran/lib/libgomp.1.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/gmm/libs/gmm.so
  Reason: image not found
> sessionInfo()
R version 4.0.0 (2020-04-24)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.4

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6      pillar_1.4.4      compiler_4.0.0    plyr_1.8.6        prettyunits_1.1.1
 [6] tools_4.0.0       progress_1.2.2    boot_1.3-24       lifecycle_0.2.0   tibble_3.0.1     
[11] nlme_3.1-147      lattice_0.20-41   pkgconfig_2.0.3   rlang_0.4.6       Matrix_1.2-18    
[16] rstudioapi_0.11   mvtnorm_1.1-0     metafor_2.4-0     dplyr_0.8.5       stringr_1.4.0    
[21] vctrs_0.3.0       hms_0.5.3         stats4_4.0.0      grid_4.0.0        tidyselect_1.1.0 
[26] glue_1.4.1        data.table_1.12.8 R6_2.4.1          purrr_0.3.4       reshape2_1.4.4   
[31] tidyr_1.1.0       magrittr_1.5      ellipsis_0.3.1    MASS_7.3-51.5     assertthat_0.2.1 
[36] sandwich_2.5-1    nor1mix_1.3-0     stringi_1.4.6     crayon_1.3.4      zoo_1.8-8

**Comment by bwiernik** [comment]
The error you are getting is happening before anything in psychmeta's .onAttach(). So, this seems to be an issue with your R/RStudio installation or package library. Do you have `R_LIBS` or `R_LIBS_USER` set on your machine so that packages are installing to a non-default location?

**Comment by bwiernik** [comment]
I'm pretty sure the issue you are having might just be that some of your packages are compiled under an older version of R. Be sure that you have a separate folder of packages for each major/minor version of R (i.e., 3.5, 3.6, 4.0; "patch" versions at the third number are fine to share packages) and don't copy packages built under an older version. Instead, re-install all packages when you update to a new major/minor version of R.

**Comment by bwiernik** [comment]
@dstanley4 I moved the package that imports gmm to Suggests. That should fix the loading issue (whatever its cause is). Can you install the development version and check: `remotes::install_github("psychmeta::psychmeta@hotfix")

**Comment by dstanley4** [comment]
I just tried but the install did not work. I tried it two ways. See below:


> remotes::install_github("psychmeta::psychmeta@hotfix")
Error in parse_repo_spec(repo) :
  Invalid git repo specification: 'psychmeta::psychmeta@hotfix'


> remotes::install_github("psychmeta/psychmeta@hotfix")
Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo psychmeta/psychmeta@hotfix
Error in utils::download.file(url, path, method = method, quiet = quiet,  :
  cannot open URL 'https://api.github.com/repos/psychmeta/psychmeta/tarball/hotfix'



On Jun 7, 2020, at 12:49 PM, Brenton M. Wiernik <notifications@github.com<mailto:notifications@github.com>> wrote:
@dstanley4<https://github.com/dstanley4> I moved the package that imports gmm to Suggests. That should fix the loading issue (whatever its cause is). Can you install the development version and check: `remotes::install_github("psychmeta::psychmeta@hotfix")

**Comment by dstanley4** [comment]
Ok - got it working.

I used:
devtools::install_github("psychmeta/psychmeta", dep = T)

No problems after that.
library(psycmeta) works fine now.

Odd. Yours is the only package I’ve had trouble with using. Re: previous comments. I had previously done a clean install of R as well removing all previous version path etc. Still not luck until this update.

 Everything seems fine now. Odd. I might not even be using the hotfix? Either way - something changed that makes it work now. I had previously done the dev version with no luck.

Much appreciated!



On Jun 7, 2020, at 12:49 PM, Brenton M. Wiernik <notifications@github.com<mailto:notifications@github.com>> wrote:




@dstanley4<https://github.com/dstanley4> I moved the package that imports gmm to Suggests. That should fix the loading issue (whatever its cause is). Can you install the development version and check: `remotes::install_github("psychmeta::psychmeta@hotfix")

**Comment by bwiernik** [comment]
Someone else confirmed that the change fixed the issue before you. So, Jeff had already merged the changes into master and deleted the hotfix branch by the time you tried to install it. The updated version is now on CRAN as well.

There seems to be something wrong with the `gmm` package that it's not working on some Macs. I haven't been able to replicate it, but there have been two reports. That dependency is only used in the simulation functions of psychmeta, so I moved it to Suggests to avoid the loading issue for most users.
